### ISSUE TITLE
Crashes device on 1.120.2

### ISSUE THREAD

**Issue by antihistamines** [Cypher01/Xglyph2#3]
Unsure whether this is a new Ingress issue or a device issue.

November build of CM13 on Peregrine, was working perfectly until I installed XGlyph2. Upon installation and activation, Google Play Services, SystemUI, and Trebuchet launcher immediately crashed. Rebooted, wiped cache to force Xposed to rebuild, same issues on reboot. Uninstalled XGlyph2, rebooted, wiped cache, phone still unusable on reboot. I had to factory reset the device from recovery to get it working again.

**Comment by Cypher01** [comment]
This seems to be a problem not related to Xglyph².

Atm I'm using Resurrection Remix v5.7.4 on OnePlus 3. I had similar problems, crashes of the launcher, Play Store, Settings, etc. Before that I was using CyanogenMod 13 and had no problems at all. First I thought it's a problem of Magisk or systemless Xposed for Magisk, but for me it turned out the problem was Integrated Timer for Ingress. I know, this is strange because it worked on CM13.

If you had to reset anyway, uninstall Integrated Timer for Ingress if you're using it or maybe try a different Xposed Framework build (original by rovo89, systemless by topjohnwu).

Anyway, I'm pretty sure the problem is not related to Xglyph².

**Comment by antihistamines** [comment]
It turned out that this was an Integrated Timer for Ingress issue after all. 

It worked for me on CM13, but I had to reflash my boot image after Magisk 13.x crashed my ROM. I must have set it up differently afterward and some combo of Magisk and Xposed works and some don't.
