### ISSUE TITLE
Support Xposed for Nougat

### ISSUE THREAD

**Issue by elmodos** [Cypher01/Xglyph2#4]
New Xposed version was released. Xglyph configuration app crashes at launch, can you check?
[XDA](https://forum.xda-developers.com/xposed/xposed-android-nougat-sdk-25-arm64-t3639221)

**Comment by Cypher01** [comment]
You have to understand, that I'm not very motivated to investigate in this problem, because the unofficial alpha version of Xposed for Nougat is uncomplete and very unstable.

I'm pretty sure that Xglyph² will work out of the box, when an official stable version of Xposed for Nougat is released. If not, I'm going to fix it as soon as I can.

You can find my full statement on [XDA](https://forum.xda-developers.com/showpost.php?p=73142598&postcount=113)
